export const initialState = {
    socketStatus: 0,
    rooms: [
        { placement: { x: 33, y: 202 }, name: 'Forurening', size: 6, availability: 0, modul: 1 },
        { placement: { x: 33, y: 265 }, name: 'Brud', size: 6, availability: 0, modul: 1 },
        { placement: { x: 33, y: 301 }, name: 'Klemt', size: 4, availability: 0, modul: 1 },
        { placement: { x: 33, y: 327 }, name: 'Byggefejl', size: 4, availability: 0, modul: 1 },
        { placement: { x: 179, y: 229 }, name: 'Driftstab', size: 10, availability: 0, modul: 1 },
        { placement: { x: 216, y: 205 }, name: 'Snetryk', size: 4, availability: 0, modul: 2 },
        { placement: { x: 216, y: 231 }, name: 'Markbrand', size: 10, availability: 0, modul: 2 },
        { placement: { x: 216, y: 278 }, name: 'Kolik', size: 4, availability: 0, modul: 2 },
        { placement: { x: 376, y: 359 }, name: 'Havari', size: 4, availability: 0, modul: 3 },
        { placement: { x: 399, y: 121 }, name: 'Påkørsel', size: 4, availability: 0, modul: 3 },
        { placement: { x: 399, y: 191 }, name: 'Sygdom', size: 4, availability: 0, modul: 3 },
        { placement: { x: 399, y: 226 }, name: 'Brand', size: 4, availability: 0, modul: 3 },
        { placement: { x: 544, y: 156 }, name: 'Uheld', size: 10, availability: 0, modul: 3 },
        { placement: { x: 582, y: 131 }, name: 'Storm', size: 4, availability: 0, modul: 4 },
        { placement: { x: 582, y: 157 }, name: 'Kollision', size: 10, availability: 0, modul: 4 },
        { placement: { x: 582, y: 204 }, name: 'Ulykke', size: 4, availability: 0, modul: 4 },
        { placement: { x: 728, y: 229 }, name: 'Skybrud', size: 10, availability: 0, modul: 4 },
        { placement: { x: 765, y: 278 }, name: 'Indbrud', size: 4, availability: 0, modul: 5 },
        { placement: { x: 765, y: 338 }, name: 'Hærværk', size: 4, availability: 0, modul: 5 },
        { placement: { x: 912, y: 303 }, name: 'Strømsvigt', size: 10, availability: 0, modul: 5 },
        { placement: { x: 948, y: 131 }, name: 'Lynnedslag', size: 4, availability: 0, modul: 6 },
        { placement: { x: 948, y: 202 }, name: 'Fugt', size: 4, availability: 0, modul: 6 },
        { placement: { x: 948, y: 228 }, name: 'Utæthed', size: 10, availability: 0, modul: 6 },
        { placement: { x: 1095, y: 156 }, name: 'Tøbrud', size: 10, availability: 0, modul: 6 },
        { placement: { x: 1132, y: 198 }, name: 'Bilskade', size: 10, availability: 0, modul: 7 },
        { placement: { x: 1132, y: 234 }, name: 'Motorstop', size: 4, availability: 0, modul: 7 },
        { placement: { x: 1132, y: 268 }, name: 'Byggesjusk', size: 10, availability: 0, modul: 7 },
        { placement: { x: 1132, y: 338 }, name: 'Nedbrud', size: 4, availability: 0, modul: 7 },
        { placement: { x: 1278, y: 302 }, name: 'Tyveri', size: 10, availability: 0, modul: 7 },
        { placement: { x: 1315, y: 195 }, name: 'Smerte', size: 4, availability: 0, modul: 8 },
        { placement: { x: 1315, y: 264 }, name: 'Stenslag', size: 4, availability: 0, modul: 8 },
        { placement: { x: 1315, y: 302 }, name: 'Fald', size: 10, availability: 0, modul: 8 },
        { placement: { x: 1315, y: 338 }, name: 'Konflikt', size: 4, availability: 0, modul: 8 }
    ]
};
